// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectManagement.TimeTracking.Infrastructure.Persistence;

#nullable disable

namespace ProjectManagement.TimeTracking.Infrastructure.Migrations
{
    [DbContext(typeof(TimeTrackingDbContext))]
    [Migration("20260426120000_AddVoidAndCorrection_TimeTracking")]
    partial class AddVoidAndCorrection_TimeTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("time_tracking")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectManagement.TimeTracking.Domain.Entities.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CostAtTime")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cost_at_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("EnteredBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entered_by");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("entry_type");

                    b.Property<decimal>("Hours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("hours");

                    b.Property<bool>("IsVoided")
                        .HasDefaultValue(false)
                        .HasColumnType("boolean")
                        .HasColumnName("is_voided");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<decimal>("RateAtTime")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("rate_at_time");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.Property<string>("VoidedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("voided_by");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("void_reason");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_time_entries_date");

                    b.HasIndex("ProjectId", "Date")
                        .HasDatabaseName("ix_time_entries_project_date");

                    b.HasIndex("ResourceId", "Date")
                        .HasDatabaseName("ix_time_entries_resource_date");

                    b.HasIndex("SupersedesId")
                        .HasDatabaseName("ix_time_entries_supersedes_id");

                    b.ToTable("time_entries", "time_tracking");
                });
#pragma warning restore 612, 618
        }
    }
}
